from .nodes import NODE_CLASS_MAPPINGS as MOON_NCM1, NODE_DISPLAY_NAME_MAPPINGS as MOON_NDNM1
from .ambient_occlusion import NODE_CLASS_MAPPINGS as MOON_NCM2, NODE_DISPLAY_NAME_MAPPINGS as MOON_NDNM2

NODE_CLASS_MAPPINGS = {**MOON_NCM1, **MOON_NCM2}
NODE_DISPLAY_NAME_MAPPINGS = {**MOON_NDNM1, **MOON_NDNM2}