from .nodes_image import NODE_CLASS_MAPPINGS as IMAGE_NCM, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_NDNM
from .nodes_tiling import NODE_CLASS_MAPPINGS as TILING_NCM, NODE_DISPLAY_NAME_MAPPINGS as TILING_NDNM
from .nodes_io import NODE_CLASS_MAPPINGS as IO_NCM, NODE_DISPLAY_NAME_MAPPINGS as IO_NDNM
from .nodes_normal import NODE_CLASS_MAPPINGS as NORMAL_NCM, NODE_DISPLAY_NAME_MAPPINGS as NORMAL_NDNM
from .nodes_height import NODE_CLASS_MAPPINGS as HEIGHT_NCM, NODE_DISPLAY_NAME_MAPPINGS as HEIGHT_NDNM
from .nodes_ao import NODE_CLASS_MAPPINGS as AO_NCM, NODE_DISPLAY_NAME_MAPPINGS as AO_NDNM
from .nodes_debug import NODE_CLASS_MAPPINGS as DEBUG_NCM, NODE_DISPLAY_NAME_MAPPINGS as DEBUG_NDNM

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

for ncm, ndnm in (
    (IMAGE_NCM, IMAGE_NDNM),
    (TILING_NCM, TILING_NDNM),
    (IO_NCM, IO_NDNM),
    (NORMAL_NCM, NORMAL_NDNM),
    (HEIGHT_NCM, HEIGHT_NDNM),
    (AO_NCM, AO_NDNM),
    (DEBUG_NCM, DEBUG_NDNM),
):
    NODE_CLASS_MAPPINGS.update(ncm)
    NODE_DISPLAY_NAME_MAPPINGS.update(ndnm)

try:
    from .nodes_pbrfusion4 import NODE_CLASS_MAPPINGS as PBRFUSION4_NCM
    from .nodes_pbrfusion4 import NODE_DISPLAY_NAME_MAPPINGS as PBRFUSION4_NDNM
    NODE_CLASS_MAPPINGS.update(PBRFUSION4_NCM)
    NODE_DISPLAY_NAME_MAPPINGS.update(PBRFUSION4_NDNM)
except ImportError as e:
    print(f"[Comfyui-moon] PBRFusion4 nodes disabled (missing dependency: {e})")
