from .nodes import NODE_CLASS_MAPPINGS as MOON_NCM1, NODE_DISPLAY_NAME_MAPPINGS as MOON_NDNM1
from .nodes_pbr import NODE_CLASS_MAPPINGS as MOON_NCM2, NODE_DISPLAY_NAME_MAPPINGS as MOON_NDNM2

from .nodes_height_diagnostics import (
    NODE_CLASS_MAPPINGS as HEIGHT_DIAGNOSTICS_NCM,
    NODE_DISPLAY_NAME_MAPPINGS as HEIGHT_DIAGNOSTICS_NDNM,
)


NODE_CLASS_MAPPINGS = {**MOON_NCM1, **MOON_NCM2}
NODE_DISPLAY_NAME_MAPPINGS = {**MOON_NDNM1, **MOON_NDNM2}

NODE_CLASS_MAPPINGS.update(HEIGHT_DIAGNOSTICS_NCM)
NODE_DISPLAY_NAME_MAPPINGS.update(HEIGHT_DIAGNOSTICS_NDNM)

try:
    from .nodes_pbrfusion4 import NODE_CLASS_MAPPINGS as PBRFUSION4_MAPPINGS
    from .nodes_pbrfusion4 import NODE_DISPLAY_NAME_MAPPINGS as PBRFUSION4_DISPLAY_MAPPINGS
    NODE_CLASS_MAPPINGS.update(PBRFUSION4_MAPPINGS)
    NODE_DISPLAY_NAME_MAPPINGS.update(PBRFUSION4_DISPLAY_MAPPINGS)
except ImportError as e:
    print(f"[Comfyui-moon] PBRFusion4 nodes disabled (missing dependency: {e})")